### PR TITLE
Allows query parameters on task assignments endpoint

### PR DESCRIPTION
**Pull request by patbenatar**
This is work originally done by @bloudermilk that I've brought in on top of latest `master` for consideration. Thoughts?

### CODE REVIEW

**Comment by bloudermilk** [comment]
Good guy @patbenatar submits my two-year-old commit as PR instead of making the simple change himself in a new one :clap:

**Comment by patbenatar** [comment]
@zmoazeni any thoughts on this?

**Comment by jadengore** [comment]
+1

**Comment by jvdp** [comment]
@patbenatar could you add a spec that shows how you use this functionality? Then I can merge it (and release it with the other 2 PR's hopefully.)

**Comment by patbenatar** [comment]
@jvdp Running the test suite locally I get some failures:

```
Failures:

  1) harvest expenses allows adding, updating, and removing expenses
     Failure/Error: category       = harvest.expense_categories.create(
     NoMethodError:
       undefined method `match' for nil:NilClass
       Did you mean?  catch
     # ./lib/harvest/behavior/crud.rb:33:in `create'
     # ./spec/functional/expenses_spec.rb:27:in `block (3 levels) in <top (required)>'
     # ./spec/functional/expenses_spec.rb:26:in `block (2 levels) in <top (required)>'

  2) harvest expenses categories allows adding, updating and removing categories
     Failure/Error: category       = harvest.expense_categories.create(
     NoMethodError:
       undefined method `match' for nil:NilClass
       Did you mean?  catch
     # ./lib/harvest/behavior/crud.rb:33:in `create'
     # ./spec/functional/expenses_spec.rb:7:in `block (4 levels) in <top (required)>'
     # ./spec/functional/expenses_spec.rb:6:in `block (3 levels) in <top (required)>'

  3) harvest invoices allows adding, updating and removing categories
     Failure/Error: cat = harvest.invoice_categories.create("name" => "New Category")
     Harvest::BadRequest:
       Harvest::BadRequest : 400 {"message":"Cannot complete your request. Parameter is missing or the value is empty: invoice_item_category"}
     # ./lib/harvest/api/base.rb:47:in `request'
     # ./lib/harvest/api/invoice_categories.rb:13:in `create'
     # ./spec/functional/invoice_spec.rb:6:in `block (3 levels) in <top (required)>'
     # ./spec/functional/invoice_spec.rb:5:in `block (2 levels) in <top (required)>'

  4) harvest reporting allows expense reporting
     Failure/Error: category = harvest.expense_categories.create(name: "Reporting category", "unit_price" => 100, "unit_name"  => "deduction")
     NoMethodError:
       undefined method `match' for nil:NilClass
       Did you mean?  catch
     # ./lib/harvest/behavior/crud.rb:33:in `create'
     # ./spec/functional/reporting_spec.rb:68:in `block (3 levels) in <top (required)>'
     # ./spec/functional/reporting_spec.rb:60:in `block (2 levels) in <top (required)>'

  5) harvest time tracking allows retrieving trackable projects and tasks
     Failure/Error: trackable_projects.first.client.should == "Bobbys Coffee Shop"
       expected: "Bobbys Coffee Shop"
            got: "Bobby's Coffee Shop" (using ==)
     # ./spec/functional/time_tracking_spec.rb:79:in `block (3 levels) in <top (required)>'
     # ./spec/functional/time_tracking_spec.rb:72:in `block (2 levels) in <top (required)>'

Finished in 5 minutes 41 seconds
63 examples, 5 failures
```

**Comment by jvdp** [comment]
@patbenatar hmm, not sure, it's been a while since I last ran the specs. It could be that it fails with some newer dependencies or perhaps due to Harvest API.

For the VCR message at least you could try `rake spec VCR_REFRESH=true`.

(The test suite needs some modernization I think...)

**Comment by zmoazeni** [comment]
Merging for 4.0 release.

**Pull request merged**
