### PR TITLE
Make expenses attachments work

### PR DESCRIPTION
**Pull request by toothfairy**

### CODE REVIEW

**Comment by jvdp** [comment]
Hi, thanks for the PR! Could you provide some comments on what you changed and perhaps add/update a test?

**Comment by toothfairy** [comment]
@jvdp the problem was with `body << "------------------------------b7edea381b46\r\n"` this line. Boundary has to end with `--`, otherwise server throws 502.

Also changed code formatting to make it a bit more readable

**Comment by jvdp** [comment]
Sounds good. Before I merge this could you add a spec? Some specification of the server response for instance would be helpful.

**Comment by toothfairy** [comment]
@jvdp I'm currently chatting with harvest support - some api endpoints don't work as intended, and that makes certain tests (including expenses related) to fail. Will update PR with test cases asap

**Comment by jvdp** [comment]
Cool! :+1:

(@patbenatar also ran into a few issues in #89)

**Comment by zmoazeni** [comment]
Gonna just merge. It'd be nice to have a spec but it doesn't have to block the PR.

FWIW, master should be easier to work with now. I've cleaned up several test problems.

**Pull request merged**
